package org.webant.queen.web.common.model;

import org.webant.queen.web.common.model.base.BaseLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Link extends BaseLink<Link> {
	public static final Link dao = new Link().dao();
}
