spring:
  datasource:
    url: jdbc:mysql://localhost/webant?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true
    username: bill
    password: sutine
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect