spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:./data/h2/webant;MODE=MYSQL
    username: webant
    password: webant
    driver-class-name: org.h2.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    joda-date-time-format: yyyy-MM-dd HH:mm:ss.SSS
    serialization:
      write_dates_as_timestamps: false
    time-zone: GMT+8
server:
  port: 8080

logging:
  file: logs/webant-queen.log
  level:
    root: INFO