spring:
  datasource:
    url: jdbc:mysql://localhost/datacubic?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true
    username: bill
    password: sutine
    driver-class-name: com.mysql.jdbc.Driver
